### PR TITLE
Upgrade to minecraft 1.12

### PR DESCRIPTION
**Pull request by nicemd**
Upgrade to minecraft 1.12

Also changed so the downloaded minecraft_server.1.12.jar is downloaded with version number still in filename and then copied by start script to minecraft_server.jar. This means the server can be upgraded without manually deleting /data/minecraft_server.jar.

### CODE REVIEW

**Comment by overshard** [comment]
This points to a different repository than the one I setup, that will need changed before merging.

**Comment by nicemd** [comment]
I created the pull request long time ago.

**Comment by overshard** [comment]
Interesting, GitHub just sent me a notification of it.

**Comment by nicemd** [comment]
:) I pushed some changes on my fork today. I didn't of this pull request..

**Pull request closed without merging**
